### ISSUE TITLE
wrong logo link

### ISSUE THREAD

**Issue by wiesehahn** [r-lidar/.github#1]
just came across this and recognised the following

```diff
-     https://raw.githubusercontent.com/r-lidar/lasR/main/man/figures/logo200x231.png
+      https://raw.githubusercontent.com/r-lidar/lasR/main/man/figures/lasR200x231.png
```

```diff
-      Compagnies
+      Companies
```

**Comment by Jean-Romain** [comment]
Yes I know it. What I didn't know is that some people are notified of any change I'm doing :smile:. It was supposed to be pseudo-private for at least one day. Just the time to get it done right. Thank you anyway.

**Comment by wiesehahn** [comment]
haha, sorry then. just came across this by accident cause I am following you on github and saw you created a repo. I promise I am not stalking.

**Comment by Jean-Romain** [comment]
I know, I know, don't worry. I didn't realize that creating a README for `r-lidar` would create a repo; otherwise, I would not have pushed the validation button haha.

I plan to create a real new repo today with more interesting stuff in it. 😉

**Comment by Jean-Romain** [comment]
:negative_squared_cross_mark:
